/// Conformed date dimension. MUST be marked as a Date Table in Power BI Desktop
/// (right-click table -> Mark as Date Table -> DATE column) for time-intelligence
/// functions (DATESYTD, SAMEPERIODLASTYEAR, DATEADD) to return correct values.
table DIM_DATES
	lineageTag: b4cf66a4-55c7-458b-be19-6f24ccc2c2e6
	dataCategory: Time

	column DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 0d5e6907-6544-44ed-a468-2be8dda238ef
		isDefaultLabel
		summarizeBy: none
		sourceColumn: DATE_KEY

		annotation SummarizationSetBy = Automatic

	column DATE
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 53a735b5-6978-4f5d-b2c9-e44469b05cbf
		summarizeBy: none
		sourceColumn: DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YEAR
		dataType: int64
		formatString: 0
		lineageTag: 75ec83fb-7478-46a4-8688-b75081936d6b
		summarizeBy: none
		sourceColumn: YEAR

		annotation SummarizationSetBy = User

	column YEAR_QUARTER
		dataType: string
		lineageTag: b34ebc78-d606-461d-a72b-faedb2de3030
		summarizeBy: none
		sourceColumn: YEAR_QUARTER

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column YEAR_MONTH
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 926fce62-b126-4e1d-b4f9-4749ac93f57c
		summarizeBy: none
		sourceColumn: YEAR_MONTH

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QUARTER_NUMBER
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 11605ecf-b884-4eca-a44a-09bdd87829a1
		summarizeBy: none
		sourceColumn: QUARTER_NUMBER

		annotation SummarizationSetBy = User

	column QUARTER_NAME
		dataType: string
		lineageTag: 543f59d4-5b7c-4773-b08e-06a3fe077f82
		summarizeBy: none
		sourceColumn: QUARTER_NAME

		annotation SummarizationSetBy = Automatic

	column MONTH
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 91bcf95c-99aa-4b71-9836-3a270a1c2200
		summarizeBy: none
		sourceColumn: MONTH

		annotation SummarizationSetBy = User

	column MONTH_NAME
		dataType: string
		lineageTag: 399a8a75-96ab-48c7-9d90-3ce2eba60092
		summarizeBy: none
		sourceColumn: MONTH_NAME
		sortByColumn: MONTH

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MONTH_YEAR
		dataType: dateTime
		formatString: Long Date
		lineageTag: 22854fdf-475c-4411-9774-26839f95436d
		summarizeBy: none
		sourceColumn: MONTH_YEAR
		sortByColumn: YEAR_MONTH

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WEEK
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ce9f366e-5509-453b-baf9-0b4c6c3cf812
		summarizeBy: none
		sourceColumn: WEEK

		annotation SummarizationSetBy = User

	column DAY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 03c000dd-0867-4f66-b710-05c78c5f1ba4
		summarizeBy: none
		sourceColumn: DAY

		annotation SummarizationSetBy = User

	column DAY_NAME
		dataType: string
		lineageTag: 0861bcbd-3276-4f0a-9b33-94b40aebb58b
		summarizeBy: none
		sourceColumn: DAY_NAME

		annotation SummarizationSetBy = Automatic

	column DAY_OF_WEEK
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 3f75fc87-fc1c-4e3b-a184-402f508f5a05
		summarizeBy: none
		sourceColumn: DAY_OF_WEEK

		annotation SummarizationSetBy = User

	column IS_WEEKEND
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		isAvailableInMdx: false
		lineageTag: 9ef5f39e-1d91-42d4-a49a-20981baf5f7e
		summarizeBy: none
		sourceColumn: IS_WEEKEND

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MONTH_INITIAL
		dataType: string
		lineageTag: defde0c6-21f1-4de0-839c-e992207cf235
		summarizeBy: none
		sourceColumn: MONTH_INITIAL
		sortByColumn: MONTH

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MONTH_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8cd7444a-11fa-4790-add0-ee0152863be9
		summarizeBy: none
		sourceColumn: MONTH_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DIM_DATES = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    DIM_DATES_Table = MARTS_Schema{[Name="DIM_DATES",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( DIM_DATES_Table ),
				    #"Changed Type" = Table.TransformColumnTypes(RemoveMetadaColumns,{{"DATE_KEY", Int64.Type}, {"DATE", type date}, {"YEAR", Int64.Type}, {"YEAR_QUARTER", type text}, {"YEAR_MONTH", type date}, {"QUARTER_NUMBER", Int64.Type}, {"QUARTER_NAME", type text}, {"MONTH", Int64.Type}, {"MONTH_NAME", type text}, {"MONTH_YEAR", type date}, {"MONTH_START_DATE", type date}, {"WEEK", Int64.Type}, {"DAY", Int64.Type}, {"DAY_NAME", type text}, {"DAY_OF_WEEK", Int64.Type}, {"IS_WEEKEND", type logical}, {"MONTH_INITIAL", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

