/// BUSINESS MEANING: Marketplace sellers (merchants), their location and each seller's primary product category. GRAIN: one row per seller. RELATIONSHIPS: joins on SELLER_KEY one-to-many to FCT_ORDER_ITEMS. Use it to analyze line-item sales by seller or seller geography.
table DIM_SELLERS
	lineageTag: 1a7fd715-ad20-46cf-b32d-5e9773ccaed1

	/// Surrogate key for a seller; primary key and fact join key. Grain: one per seller.
	column SELLER_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 5951b6c8-3555-4b50-9cea-9997bcdbcdc0
		isDefaultLabel
		summarizeBy: none
		sourceColumn: SELLER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Natural seller identifier from the source system. Grain: one per seller.
	column SELLER_ID
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 72bc7d81-1126-4eb1-84d3-e9c342125d5c
		summarizeBy: none
		sourceColumn: SELLER_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Seller's 5-digit zip code. Grain: per seller.
	column ZIP_CODE
		dataType: int64
		formatString: 0
		lineageTag: 1e09f937-706f-4157-970c-a89f6f50b73a
		summarizeBy: none
		sourceColumn: ZIP_CODE

		annotation SummarizationSetBy = Automatic

	/// Seller's city. Grain: per seller.
	column CITY
		dataType: string
		lineageTag: 33fd6afb-ee59-4428-bcb2-9fabbaad863c
		summarizeBy: none
		sourceColumn: CITY

		annotation SummarizationSetBy = Automatic

	/// Seller's US state code. Grain: per seller.
	column STATE
		dataType: string
		lineageTag: 8bc5f99b-d378-491f-9fa4-f2c6fea42195
		summarizeBy: none
		sourceColumn: STATE

		annotation SummarizationSetBy = Automatic

	/// Latitude of the seller's location. Grain: per seller.
	column LATITUDE
		dataType: double
		lineageTag: e79f4396-1b1d-4f71-aa11-2b2777e4872b
		summarizeBy: none
		sourceColumn: LATITUDE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Longitude of the seller's location. Grain: per seller.
	column LONGITUDE
		dataType: double
		lineageTag: 073adbe2-9bc3-4f98-8c1a-5bf345116cb3
		summarizeBy: none
		sourceColumn: LONGITUDE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// The category (English) this seller sells most; 'Unknown' if none. Grain: per seller.
	column PRIMARY_PRODUCT_CATEGORY
		dataType: string
		lineageTag: 492b6422-dfe4-4fec-8997-4463991f50e2
		summarizeBy: none
		sourceColumn: PRIMARY_PRODUCT_CATEGORY

		annotation SummarizationSetBy = Automatic

	partition DIM_SELLERS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    DIM_SELLERS_Table = MARTS_Schema{[Name="DIM_SELLERS",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( DIM_SELLERS_Table ),
				    #"Changed Type" = Table.TransformColumnTypes(RemoveMetadaColumns,{{"SELLER_KEY", type text}, {"SELLER_ID", type text}, {"ZIP_CODE", Int64.Type}, {"CITY", type text}, {"STATE", type text}, {"LATITUDE", type number}, {"LONGITUDE", type number}, {"PRIMARY_PRODUCT_CATEGORY", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

