/// BUSINESS MEANING: Product catalog (category and name). GRAIN: one row per product. RELATIONSHIPS: joins on PRODUCT_KEY one-to-many to FCT_ORDER_ITEMS (product sold) and to FCT_MARKET_BASKET (active on product A; inactive on product B). Use it to analyze sales and basket affinity by product or category.
table DIM_PRODUCTS
	lineageTag: d13f411b-6e61-4583-af51-62ff5350c900

	/// Surrogate key for a product; primary key and fact join key. Grain: one per product.
	column PRODUCT_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 56a44d8a-61dd-4c57-9014-0e2efb62dae4
		isDefaultLabel
		summarizeBy: none
		sourceColumn: PRODUCT_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Natural product identifier from the source system. Grain: one per product.
	column PRODUCT_ID
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 77bbe0f2-ec29-4a88-923f-424baa1b11a2
		summarizeBy: none
		sourceColumn: PRODUCT_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Product category in English; primary attribute for category-level sales analysis. Grain: per product.
	column PRODUCT_CATEGORY
		dataType: string
		lineageTag: f1f679e5-aa0f-45d7-ae8c-e9c13334b0f9
		summarizeBy: none
		sourceColumn: PRODUCT_CATEGORY

		annotation SummarizationSetBy = Automatic

	/// Display name of the product. Grain: per product.
	column PRODUCT_NAME
		dataType: string
		lineageTag: e1278c07-67ec-4ddb-9346-6f8421ba6f12
		summarizeBy: none
		sourceColumn: PRODUCT_NAME

		annotation SummarizationSetBy = Automatic

	partition DIM_PRODUCTS = m
		mode: import
		source =
				let
					Source = Snowflake.Databases(
						"IFBLGEP-XM39851.snowflakecomputing.com", "ECOMMERCE_RETAIL_WH", [Implementation = "1.0"]
					),
					ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name = "ECOMMERCE_RETAIL_DB_PROD", Kind = "Database"]}[Data],
					MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name = "MARTS", Kind = "Schema"]}[Data],
					DIM_PRODUCTS_Table = MARTS_Schema{[Name = "DIM_PRODUCTS", Kind = "Table"]}[Data],
					RemoveMetadaColumns = fnRemoveMetadataColumns( DIM_PRODUCTS_Table ),
				    #"Changed Type" = Table.TransformColumnTypes(RemoveMetadaColumns,{{"PRODUCT_KEY", type text}, {"PRODUCT_ID", type text}, {"PRODUCT_NAME", type text}, {"PRODUCT_CATEGORY", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

