table FCT_CLV_CUSTOMER
	lineageTag: b544e3f2-4033-4220-a741-c0e080343fc5

	column CUSTOMER_UNIQUE_ID
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 2d8577ab-79cf-47da-8744-f3e5a0af2561
		summarizeBy: none
		sourceColumn: CUSTOMER_UNIQUE_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 50ffa236-d8ca-46d6-abc4-d77af91f09df
		isDefaultLabel
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COHORT_MONTH
		dataType: dateTime
		formatString: Short Date
		lineageTag: 26da7171-fed6-475f-b677-9bf0a6defcdb
		summarizeBy: none
		sourceColumn: COHORT_MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FIRST_ORDER_DATE
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4bfb9560-c5ec-49dc-bcc5-4f025a5f510e
		summarizeBy: none
		sourceColumn: FIRST_ORDER_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LAST_ORDER_DATE
		dataType: dateTime
		formatString: Short Date
		lineageTag: fc7fa9c6-68d9-44a5-b5df-ce7b7e31de4d
		summarizeBy: none
		sourceColumn: LAST_ORDER_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TOTAL_LIFETIME_ORDERS
		dataType: int64
		formatString: 0
		lineageTag: 79e297c0-dd8f-4284-8e0e-97673a37df6e
		summarizeBy: none
		sourceColumn: TOTAL_LIFETIME_ORDERS

		annotation SummarizationSetBy = Automatic

	column TOTAL_LIFETIME_REVENUE
		dataType: decimal
		formatString: 0.00
		lineageTag: 08a0e96a-6f8c-40f8-a38e-4c6091e61d77
		summarizeBy: sum
		sourceColumn: TOTAL_LIFETIME_REVENUE

		annotation SummarizationSetBy = Automatic

	column HISTORICAL_AOV
		dataType: decimal
		formatString: 0.00
		lineageTag: ba353c5b-92f4-42b9-b26b-f69bf3a3a70b
		summarizeBy: sum
		sourceColumn: HISTORICAL_AOV

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_LIFESPAN_DAYS
		dataType: int64
		formatString: 0
		lineageTag: 745cfde4-fd15-476f-8356-f6ec9d007833
		summarizeBy: none
		sourceColumn: CUSTOMER_LIFESPAN_DAYS

		annotation SummarizationSetBy = Automatic

	column TOTAL_REVIEWS
		dataType: int64
		formatString: 0
		lineageTag: 4fb5fc51-2029-4f6a-88f7-f897d31272a6
		summarizeBy: none
		sourceColumn: TOTAL_REVIEWS

		annotation SummarizationSetBy = Automatic

	column AVERAGE_RATING
		dataType: int64
		formatString: 0
		lineageTag: 2aa99691-414d-47a5-9278-d000e875949a
		summarizeBy: none
		sourceColumn: AVERAGE_RATING

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_LIFECYCLE_SEGMENT
		dataType: string
		lineageTag: 429288aa-9f9d-4097-ab00-d7a30759119a
		summarizeBy: none
		sourceColumn: CUSTOMER_LIFECYCLE_SEGMENT

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_VALUE_SEGMENT
		dataType: string
		lineageTag: db9cae5c-4434-40a5-a2db-e7451a7ab191
		summarizeBy: none
		sourceColumn: CUSTOMER_VALUE_SEGMENT

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_SATISFACTION_SEGMENT
		dataType: string
		lineageTag: 01d35262-8042-4fe1-b415-5c48d0219dad
		summarizeBy: none
		sourceColumn: CUSTOMER_SATISFACTION_SEGMENT

		annotation SummarizationSetBy = Automatic

	column PREDICTED_CLV_12M
		dataType: decimal
		formatString: 0.00
		lineageTag: a2c05c1f-c156-41b3-9d3b-0e7654480a1c
		summarizeBy: sum
		sourceColumn: PREDICTED_CLV_12M

		annotation SummarizationSetBy = Automatic

	partition FCT_CLV_CUSTOMER = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_CLV_CUSTOMER_Table = MARTS_Schema{[Name="FCT_CLV_CUSTOMER",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_CLV_CUSTOMER_Table ),
				    #"Changed Type" = Table.TransformColumnTypes(RemoveMetadaColumns,{{"CUSTOMER_KEY", type text}, {"CUSTOMER_UNIQUE_ID", type text}, {"COHORT_MONTH", type date}, {"FIRST_ORDER_DATE", type date}, {"LAST_ORDER_DATE", type date}, {"TOTAL_LIFETIME_ORDERS", Int64.Type}, {"TOTAL_LIFETIME_REVENUE", Currency.Type}, {"HISTORICAL_AOV", Currency.Type}, {"CUSTOMER_LIFESPAN_DAYS", Int64.Type}, {"TOTAL_REVIEWS", Int64.Type}, {"AVERAGE_RATING", type number}, {"CUSTOMER_LIFECYCLE_SEGMENT", type text}, {"CUSTOMER_VALUE_SEGMENT", type text}, {"CUSTOMER_SATISFACTION_SEGMENT", type text}, {"PREDICTED_CLV_12M", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

