/// BUSINESS MEANING: Order-header facts - the core sales and operations table capturing revenue, fulfillment timing and review outcome for each order. Primary source for order volume, revenue, AOV, on-time delivery and satisfaction. GRAIN: one row per order. RELATIONSHIPS: joins to DIM_CUSTOMERS (CUSTOMER_KEY) and to DIM_DATES on order date (active); an inactive delivery-date join enables delivery-timing analysis. Not directly related to FCT_ORDER_ITEMS or FCT_ORDER_PAYMENTS (separate facts joined only through shared dimensions).
table FCT_ORDERS
	lineageTag: 75a2ace9-4107-4c92-8e4e-a8d4733f9e84

	/// Surrogate key of the order; primary key of this fact. Grain: one per order.
	column ORDER_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 7ca1aa79-170c-4aa8-af69-9b157790d237
		summarizeBy: none
		sourceColumn: ORDER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Customer who placed the order; join to DIM_CUSTOMERS. Grain: per order.
	column CUSTOMER_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: aea5a544-421f-4a41-bef7-d6598bb4263f
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Order placement date; active join to DIM_DATES. Grain: per order.
	column ORDER_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 440d2e17-04af-4c2f-9863-09f7a85e9c1c
		summarizeBy: none
		sourceColumn: ORDER_DATE_KEY

		annotation SummarizationSetBy = Automatic

	/// Order approval date (YYYYMMDD); no active relationship, used for approval-timing measures. Grain: per order.
	column APPROVAL_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 0d0f3a9c-9589-4593-b9ca-93f849eee367
		summarizeBy: none
		sourceColumn: APPROVAL_DATE_KEY

		annotation SummarizationSetBy = Automatic

	/// Customer delivery date; inactive join to DIM_DATES (activate to analyze by delivery date). Grain: per order.
	column DELIVERY_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: e4a4fc2f-e179-4582-8547-9829bdc773d9
		summarizeBy: none
		sourceColumn: DELIVERY_DATE_KEY

		annotation SummarizationSetBy = Automatic

	/// Promised/estimated delivery date (YYYYMMDD). Grain: per order.
	column ESTIMATED_DELIVERY_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: e5df83e2-7ada-4999-b836-c571513ccbe6
		summarizeBy: none
		sourceColumn: ESTIMATED_DELIVERY_DATE_KEY

		annotation SummarizationSetBy = Automatic

	/// Order lifecycle status (delivered, shipped, canceled, invoiced, processing, approved, unavailable). Grain: per order.
	column ORDER_STATUS
		dataType: string
		lineageTag: 6d0bfc68-ae5a-45a5-9522-ec3a01674133
		summarizeBy: none
		sourceColumn: ORDER_STATUS

		annotation SummarizationSetBy = Automatic

	/// Actual days from order placement to delivery; NULL if not delivered. Grain: per order.
	column DELIVERY_DAYS
		dataType: int64
		formatString: 0
		lineageTag: cd42f331-3a40-42c9-b606-5d01ee70b4ed
		summarizeBy: none
		sourceColumn: DELIVERY_DAYS

		annotation SummarizationSetBy = Automatic

	/// Days from approval to delivery; NULL if not delivered. Grain: per order.
	column FULFILLMENT_DAYS
		dataType: int64
		formatString: 0
		lineageTag: dc51586b-7cf7-4695-96cb-12b729ea98dc
		summarizeBy: none
		sourceColumn: FULFILLMENT_DAYS

		annotation SummarizationSetBy = Automatic

	/// Days from carrier pickup to delivery; NULL if not delivered. Grain: per order.
	column SHIPPING_TRANSIT_DAYS
		dataType: int64
		formatString: 0
		lineageTag: 93bbae7a-3768-44cd-88f6-e6da238abb07
		summarizeBy: none
		sourceColumn: SHIPPING_TRANSIT_DAYS

		annotation SummarizationSetBy = Automatic

	/// Flag: delivered on or before the estimated date; NULL if not delivered. Grain: per order.
	column IS_ON_TIME_DELIVERY
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: db69813c-c16a-434e-bc3a-6a0bff3cbc99
		summarizeBy: none
		sourceColumn: IS_ON_TIME_DELIVERY

		annotation SummarizationSetBy = Automatic

	/// Merchandise value of the order excluding freight (BRL). Grain: per order.
	column TOTAL_PRICE
		dataType: decimal
		formatString: 0.00
		lineageTag: 98a630fb-5b18-4b60-8428-75c33c7397b0
		summarizeBy: none
		sourceColumn: TOTAL_PRICE

		annotation SummarizationSetBy = Automatic

	/// Freight/shipping charged on the order (BRL). Grain: per order.
	column TOTAL_FREIGHT_VALUE
		dataType: decimal
		formatString: 0.00
		lineageTag: d52982e4-ff6f-436b-898d-eb12b4227580
		summarizeBy: none
		sourceColumn: TOTAL_FREIGHT_VALUE

		annotation SummarizationSetBy = Automatic

	/// Order value including freight (price + freight, BRL). Grain: per order.
	column GROSS_ORDER_VALUE
		dataType: int64
		formatString: 0
		lineageTag: da681881-a182-4864-824f-93484eafbbde
		summarizeBy: none
		sourceColumn: GROSS_ORDER_VALUE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	/// Number of payment installments on the order. Grain: per order.
	column PAYMENT_COUNT
		dataType: int64
		formatString: 0
		lineageTag: 49ff3acf-7354-47ef-8d5a-a3f1425c1c49
		summarizeBy: none
		sourceColumn: PAYMENT_COUNT

		annotation SummarizationSetBy = Automatic

	/// Total amount actually paid for the order (BRL); the primary source of the Total Revenue measure. Grain: per order.
	column TOTAL_PAYMENT_VALUE
		dataType: int64
		formatString: 0
		lineageTag: f0b22108-b161-42ea-9f83-7045385fdd6f
		summarizeBy: none
		sourceColumn: TOTAL_PAYMENT_VALUE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	/// Number of reviews submitted for the order. Grain: per order.
	column REVIEW_COUNT
		dataType: int64
		formatString: 0
		lineageTag: ef1ef2f3-f3fc-484e-acc7-4114f56eddcc
		summarizeBy: none
		sourceColumn: REVIEW_COUNT

		annotation SummarizationSetBy = Automatic

	/// Order's review score, 1-5. Grain: per order.
	column REVIEW_SCORE
		dataType: int64
		formatString: 0
		lineageTag: ab770784-d218-4f60-ab57-1213f0b3be9b
		summarizeBy: none
		sourceColumn: REVIEW_SCORE

		annotation SummarizationSetBy = Automatic

	/// Calendar date the order was placed. Grain: per order.
	column ORDER_DATE
		dataType: dateTime
		isHidden
		formatString: Short Date
		isAvailableInMdx: false
		lineageTag: 37cf1984-c8be-430c-a280-9ecd09fdd099
		summarizeBy: none
		sourceColumn: ORDER_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FCT_ORDERS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_ORDERS_Table = MARTS_Schema{[Name="FCT_ORDERS",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_ORDERS_Table ),
				    #"Removed Columns" = Table.RemoveColumns(RemoveMetadaColumns,{"ORDER_ID", "CUSTOMER_UNIQUE_ID"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"ORDER_KEY", Int64.Type}, {"CUSTOMER_KEY", Int64.Type}, {"ORDER_DATE_KEY", Int64.Type}, {"APPROVAL_DATE_KEY", Int64.Type}, {"DELIVERY_DATE_KEY", Int64.Type}, {"ESTIMATED_DELIVERY_DATE_KEY", Int64.Type}, {"ORDER_DATE", type date}, {"ORDER_STATUS", type text}, {"DELIVERY_DAYS", Int64.Type}, {"FULFILLMENT_DAYS", Int64.Type}, {"SHIPPING_TRANSIT_DAYS", Int64.Type}, {"IS_ON_TIME_DELIVERY", type logical}, {"TOTAL_PRICE", Currency.Type}, {"TOTAL_FREIGHT_VALUE", Currency.Type}, {"GROSS_ORDER_VALUE", Currency.Type}, {"PAYMENT_COUNT", Int64.Type}, {"TOTAL_PAYMENT_VALUE", Currency.Type}, {"REVIEW_COUNT", Int64.Type}, {"REVIEW_SCORE", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

