table FCT_COHORT_RETENTION
	lineageTag: 202dd212-ce20-40d4-a849-593f800ab56b

	column COHORT_RETENTION_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 7fa257d0-ad3d-43e3-b687-c79e5754ef9b
		summarizeBy: none
		sourceColumn: COHORT_RETENTION_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COHORT_MONTH
		dataType: dateTime
		formatString: Short Date
		lineageTag: bc2aa055-7cca-4614-89e5-a5e57d00f4e1
		summarizeBy: none
		sourceColumn: COHORT_MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ACTIVE_CUSTOMERS
		dataType: int64
		formatString: 0
		lineageTag: 0906f4ab-37c1-42e4-8aab-a94ac2acf6b8
		summarizeBy: none
		sourceColumn: ACTIVE_CUSTOMERS

		annotation SummarizationSetBy = User

	column COHORT_SIZE
		dataType: int64
		formatString: #,0
		lineageTag: 8f2daaf8-b784-4f89-b5bb-2d057b98f34e
		summarizeBy: none
		sourceColumn: COHORT_SIZE

		annotation SummarizationSetBy = User

	column PERIOD_ORDERS
		dataType: int64
		formatString: #,0
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890
		summarizeBy: none
		sourceColumn: PERIOD_ORDERS

		annotation SummarizationSetBy = User

	column PERIOD_REVENUE
		dataType: decimal
		formatString: \$#,0.00;-\$#,0.00;\$#,0.00
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678901
		summarizeBy: sum
		sourceColumn: PERIOD_REVENUE

		annotation SummarizationSetBy = Automatic

	column PERIOD
		dataType: int64
		formatString: 0
		lineageTag: aa2d79af-cd67-4f06-96dd-bfeae24010bd
		summarizeBy: none
		sourceColumn: PERIOD

		annotation SummarizationSetBy = User

	column GROSS_RETAINED_REVENUE
		dataType: decimal
		lineageTag: 1b5773b2-11f4-4a7d-aa78-de10c0822ac7
		summarizeBy: sum
		sourceColumn: GROSS_RETAINED_REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NET_RETAINED_REVENUE
		dataType: decimal
		lineageTag: 097592ff-6511-486f-acbc-f65798e88502
		summarizeBy: sum
		sourceColumn: NET_RETAINED_REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COHORT_INITIAL_REVENUE
		dataType: decimal
		lineageTag: ca1a625b-7ea1-45d4-aff1-96b27c148da9
		summarizeBy: sum
		sourceColumn: COHORT_INITIAL_REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COHORT_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 4589f4ec-1063-48fe-b858-df8edb73e658
		summarizeBy: none
		sourceColumn: COHORT_DATE_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FCT_COHORT_RETENTION = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_COHORT_RETENTION_Table = MARTS_Schema{[Name="FCT_COHORT_RETENTION",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_COHORT_RETENTION_Table ),
				    #"Changed Type" = Table.TransformColumnTypes(RemoveMetadaColumns,{{"COHORT_RETENTION_KEY", type text}, {"COHORT_DATE_KEY", Int64.Type}, {"COHORT_MONTH", type date}, {"COHORT_SIZE", Int64.Type}, {"PERIOD", Int64.Type}, {"ACTIVE_CUSTOMERS", Int64.Type}, {"PERIOD_ORDERS", Int64.Type}, {"PERIOD_REVENUE", Currency.Type}, {"GROSS_RETAINED_REVENUE", Currency.Type}, {"NET_RETAINED_REVENUE", Currency.Type}, {"COHORT_INITIAL_REVENUE", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

