table FCT_ORDER_ITEMS
	lineageTag: 0e4f458f-0dfd-4cf5-bd7e-68cdfbb34b61

	column ORDER_ITEM_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 4f1830be-1345-4eb1-bcb4-79e0c0b8573b
		summarizeBy: none
		sourceColumn: ORDER_ITEM_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDER_ID
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 0663d774-8ae0-4915-a97b-918a3fd6457b
		summarizeBy: none
		sourceColumn: ORDER_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDER_ITEM_ID
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: d921a3cc-1654-4d25-b006-003304af1213
		summarizeBy: none
		sourceColumn: ORDER_ITEM_ID

		annotation SummarizationSetBy = User

	column CUSTOMER_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: ee7918b3-d9d1-4fc8-865b-959a0e499954
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PRODUCT_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 02f19c43-e4c5-412d-9a21-5399bfab28fb
		summarizeBy: none
		sourceColumn: PRODUCT_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SELLER_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 8b14c6d6-4847-4dda-804e-c1a9a3fb0f66
		summarizeBy: none
		sourceColumn: SELLER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDER_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 575c141a-f7d4-4ffc-8515-07022b071ac9
		summarizeBy: none
		sourceColumn: ORDER_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column DELIVERY_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 60b64be3-8929-4e0d-be7a-75cc15f211b1
		summarizeBy: none
		sourceColumn: DELIVERY_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column ORDER_STATUS
		dataType: string
		lineageTag: 77c9cb4e-f7b0-4752-a9f4-2f938321d477
		summarizeBy: none
		sourceColumn: ORDER_STATUS

		annotation SummarizationSetBy = Automatic

	column ITEM_PRICE
		dataType: decimal
		formatString: 0.00
		lineageTag: e2a76e35-c94e-4b92-ba73-8fd8240cbbd0
		summarizeBy: sum
		sourceColumn: ITEM_PRICE

		annotation SummarizationSetBy = Automatic

	column ITEM_FREIGHT
		dataType: decimal
		formatString: 0.00
		lineageTag: ff9a123d-6527-4b7d-a886-a97eebd9e1da
		summarizeBy: sum
		sourceColumn: ITEM_FREIGHT

		annotation SummarizationSetBy = Automatic

	column ITEM_TOTAL
		dataType: decimal
		formatString: 0.00
		lineageTag: 896c1e02-dd3c-4fdc-80a4-bfc52f30dc59
		summarizeBy: sum
		sourceColumn: ITEM_TOTAL

		annotation SummarizationSetBy = Automatic

	column PRODUCT_ID
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: eec05277-a35e-43ac-90c8-75c6192b1edc
		summarizeBy: none
		sourceColumn: PRODUCT_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SELLER_ID
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 834e5dc3-1365-4670-b7ce-b7252ffc49a3
		summarizeBy: none
		sourceColumn: SELLER_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDER_DATE
		dataType: dateTime
		isHidden
		formatString: Short Date
		isAvailableInMdx: false
		lineageTag: 54812cc5-42cc-4018-afa5-997a24c4d81a
		summarizeBy: none
		sourceColumn: ORDER_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FCT_ORDER_ITEMS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_ORDER_ITEMS_Table = MARTS_Schema{[Name="FCT_ORDER_ITEMS",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_ORDER_ITEMS_Table ),
				    #"Changed Type" = Table.TransformColumnTypes(RemoveMetadaColumns,{{"ORDER_ITEM_KEY", type text}, {"ORDER_ID", type text}, {"ORDER_ITEM_ID", Int64.Type}, {"PRODUCT_ID", type text}, {"SELLER_ID", type text}, {"CUSTOMER_KEY", type text}, {"PRODUCT_KEY", type text}, {"SELLER_KEY", type text}, {"ORDER_DATE_KEY", Int64.Type}, {"DELIVERY_DATE_KEY", Int64.Type}, {"ORDER_DATE", type date}, {"ORDER_STATUS", type text}, {"ITEM_PRICE", Currency.Type}, {"ITEM_FREIGHT", Currency.Type}, {"ITEM_TOTAL", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

