table FCT_ORDERS
	lineageTag: 75a2ace9-4107-4c92-8e4e-a8d4733f9e84

	column ORDER_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 7ca1aa79-170c-4aa8-af69-9b157790d237
		summarizeBy: none
		sourceColumn: ORDER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDER_ID
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 4d9e4274-e1ad-4712-bbaa-67d0f25a2389
		summarizeBy: none
		sourceColumn: ORDER_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_KEY
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: aea5a544-421f-4a41-bef7-d6598bb4263f
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDER_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 440d2e17-04af-4c2f-9863-09f7a85e9c1c
		summarizeBy: none
		sourceColumn: ORDER_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column APPROVAL_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 0d0f3a9c-9589-4593-b9ca-93f849eee367
		summarizeBy: none
		sourceColumn: APPROVAL_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column DELIVERY_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: e4a4fc2f-e179-4582-8547-9829bdc773d9
		summarizeBy: none
		sourceColumn: DELIVERY_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column ESTIMATED_DELIVERY_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: e5df83e2-7ada-4999-b836-c571513ccbe6
		summarizeBy: none
		sourceColumn: ESTIMATED_DELIVERY_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column ORDER_STATUS
		dataType: string
		lineageTag: 6d0bfc68-ae5a-45a5-9522-ec3a01674133
		summarizeBy: none
		sourceColumn: ORDER_STATUS

		annotation SummarizationSetBy = Automatic

	column DELIVERY_DAYS
		dataType: int64
		formatString: 0
		lineageTag: cd42f331-3a40-42c9-b606-5d01ee70b4ed
		summarizeBy: none
		sourceColumn: DELIVERY_DAYS

		annotation SummarizationSetBy = Automatic

	column FULFILLMENT_DAYS
		dataType: int64
		formatString: 0
		lineageTag: dc51586b-7cf7-4695-96cb-12b729ea98dc
		summarizeBy: none
		sourceColumn: FULFILLMENT_DAYS

		annotation SummarizationSetBy = Automatic

	column SHIPPING_TRANSIT_DAYS
		dataType: int64
		formatString: 0
		lineageTag: 93bbae7a-3768-44cd-88f6-e6da238abb07
		summarizeBy: none
		sourceColumn: SHIPPING_TRANSIT_DAYS

		annotation SummarizationSetBy = Automatic

	column IS_ON_TIME_DELIVERY
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: db69813c-c16a-434e-bc3a-6a0bff3cbc99
		summarizeBy: none
		sourceColumn: IS_ON_TIME_DELIVERY

		annotation SummarizationSetBy = Automatic

	column TOTAL_PRICE
		dataType: decimal
		formatString: 0.00
		lineageTag: 98a630fb-5b18-4b60-8428-75c33c7397b0
		summarizeBy: sum
		sourceColumn: TOTAL_PRICE

		annotation SummarizationSetBy = Automatic

	column TOTAL_FREIGHT_VALUE
		dataType: decimal
		formatString: 0.00
		lineageTag: d52982e4-ff6f-436b-898d-eb12b4227580
		summarizeBy: sum
		sourceColumn: TOTAL_FREIGHT_VALUE

		annotation SummarizationSetBy = Automatic

	column GROSS_ORDER_VALUE
		dataType: int64
		formatString: 0
		lineageTag: da681881-a182-4864-824f-93484eafbbde
		summarizeBy: none
		sourceColumn: GROSS_ORDER_VALUE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column PAYMENT_COUNT
		dataType: int64
		formatString: 0
		lineageTag: 49ff3acf-7354-47ef-8d5a-a3f1425c1c49
		summarizeBy: none
		sourceColumn: PAYMENT_COUNT

		annotation SummarizationSetBy = Automatic

	column TOTAL_PAYMENT_VALUE
		dataType: int64
		formatString: 0
		lineageTag: f0b22108-b161-42ea-9f83-7045385fdd6f
		summarizeBy: none
		sourceColumn: TOTAL_PAYMENT_VALUE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column REVIEW_COUNT
		dataType: int64
		formatString: 0
		lineageTag: ef1ef2f3-f3fc-484e-acc7-4114f56eddcc
		summarizeBy: none
		sourceColumn: REVIEW_COUNT

		annotation SummarizationSetBy = Automatic

	column REVIEW_SCORE
		dataType: int64
		formatString: 0
		lineageTag: ab770784-d218-4f60-ab57-1213f0b3be9b
		summarizeBy: none
		sourceColumn: REVIEW_SCORE

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_UNIQUE_ID
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: a5cc8834-b8e5-433c-a6fa-c589f4474d55
		summarizeBy: none
		sourceColumn: CUSTOMER_UNIQUE_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ORDER_DATE
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 37cf1984-c8be-430c-a280-9ecd09fdd099
		summarizeBy: none
		sourceColumn: ORDER_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FCT_ORDERS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_ORDERS_Table = MARTS_Schema{[Name="FCT_ORDERS",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_ORDERS_Table ),
				    #"Changed Type" = Table.TransformColumnTypes(RemoveMetadaColumns,{{"ORDER_KEY", type text}, {"ORDER_ID", type text}, {"CUSTOMER_KEY", type text}, {"CUSTOMER_UNIQUE_ID", type text}, {"ORDER_DATE_KEY", Int64.Type}, {"APPROVAL_DATE_KEY", Int64.Type}, {"DELIVERY_DATE_KEY", Int64.Type}, {"ESTIMATED_DELIVERY_DATE_KEY", Int64.Type}, {"ORDER_DATE", type date}, {"ORDER_STATUS", type text}, {"DELIVERY_DAYS", Int64.Type}, {"FULFILLMENT_DAYS", Int64.Type}, {"SHIPPING_TRANSIT_DAYS", Int64.Type}, {"IS_ON_TIME_DELIVERY", type logical}, {"TOTAL_PRICE", Currency.Type}, {"TOTAL_FREIGHT_VALUE", Currency.Type}, {"GROSS_ORDER_VALUE", Currency.Type}, {"PAYMENT_COUNT", Int64.Type}, {"TOTAL_PAYMENT_VALUE", Currency.Type}, {"REVIEW_COUNT", Int64.Type}, {"REVIEW_SCORE", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

