-- =================================================
-- E-COMMERCE RETAIL ANALYTICS
-- 4. Grant Access Configuration
-- =================================================
-- Run as: ACCOUNTADMIN (or SECURITYADMIN for grants)
-- Purpose: All permission grants in one place
-- Dependencies: Run after files 1, 2, and 3
-- =================================================

USE ROLE ACCOUNTADMIN;

-- =================================================
-- WAREHOUSE GRANTS
-- =================================================

GRANT USAGE, OPERATE ON WAREHOUSE ECOMMERCE_RETAIL_WH
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

GRANT USAGE ON WAREHOUSE ECOMMERCE_RETAIL_WH
    TO ROLE BI_READONLY_ROLE;


-- =================================================
-- DEV DATABASE GRANTS
-- =================================================
GRANT USAGE ON DATABASE ECOMMERCE_RETAIL_DB_DEV
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- CREATE SCHEMA needed for CI to create isolated PR schemas (CI_PR_xxx)
GRANT CREATE SCHEMA ON DATABASE ECOMMERCE_RETAIL_DB_DEV
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- DEV SCHEMAS GRANTS - LEAD_DATA_ENGINEER_ROLE
-- Bronze Layer: RAW - Full access for data loading
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE PIPE
    ON SCHEMA ECOMMERCE_RETAIL_DB_DEV.RAW
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- Silver Layer: STAGING - Create views
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA ECOMMERCE_RETAIL_DB_DEV.STAGING
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- Gold Layer: INTERMEDIATE + MARTS - Create tables (fact & dimensions)
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA ECOMMERCE_RETAIL_DB_DEV.INTERMEDIATE
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA ECOMMERCE_RETAIL_DB_DEV.MARTS
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- DEV TABLES/VIEWS GRANTS - LEAD_DATA_ENGINEER_ROLE
-- Tables
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN DATABASE ECOMMERCE_RETAIL_DB_DEV
    TO ROLE LEAD_DATA_ENGINEER_ROLE;
    
-- Views 
GRANT SELECT
    ON ALL VIEWS IN DATABASE ECOMMERCE_RETAIL_DB_DEV
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- DEV FUTURE GRANTS (if new schemas/tables/views are added)
-- Future schemas
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ECOMMERCE_RETAIL_DB_DEV
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- Future tables
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN DATABASE ECOMMERCE_RETAIL_DB_DEV
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- Future views 
GRANT SELECT
    ON FUTURE VIEWS IN DATABASE ECOMMERCE_RETAIL_DB_DEV
    TO ROLE LEAD_DATA_ENGINEER_ROLE;


-- =================================================
-- PROD DATABASE GRANTS - LEAD_DATA_ENGINEER_ROLE
-- =================================================
GRANT USAGE ON DATABASE ECOMMERCE_RETAIL_DB_PROD
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- PROD SCHEMAS GRANTS - LEAD_DATA_ENGINEER_ROLE
-- Gold Layer: INTERMEDIATE + MARTS - Create tables (fact & dimensions)
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA ECOMMERCE_RETAIL_DB_PROD.INTERMEDIATE
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA ECOMMERCE_RETAIL_DB_PROD.MARTS
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- PROD TABLES/VIEWS GRANTS - LEAD_DATA_ENGINEER_ROLE
-- Tables
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN DATABASE ECOMMERCE_RETAIL_DB_PROD
    TO ROLE LEAD_DATA_ENGINEER_ROLE;
    
-- Views
GRANT SELECT
    ON ALL VIEWS IN DATABASE ECOMMERCE_RETAIL_DB_PROD
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- PROD FUTURE GRANTS - LEAD_DATA_ENGINEER_ROLE (if new schemas/tables/views are added)
-- Future schemas
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ECOMMERCE_RETAIL_DB_PROD
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- Future tables
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN DATABASE ECOMMERCE_RETAIL_DB_PROD
    TO ROLE LEAD_DATA_ENGINEER_ROLE;

-- Future views
GRANT SELECT
    ON FUTURE VIEWS IN DATABASE ECOMMERCE_RETAIL_DB_PROD
    TO ROLE LEAD_DATA_ENGINEER_ROLE;



-- =================================================
-- PROD DATABASE GRANTS - BI_READONLY_ROLE
-- =================================================
GRANT USAGE ON DATABASE ECOMMERCE_RETAIL_DB_PROD
    TO ROLE BI_READONLY_ROLE;

-- PROD SCHEMA GRANTS - BI_READONLY_ROLE
-- BI role only needs access to MARTS
GRANT USAGE ON SCHEMA ECOMMERCE_RETAIL_DB_PROD.MARTS
    TO ROLE BI_READONLY_ROLE;

-- PROD TABLE/VIEW GRANTS - BI_READONLY_ROLE
-- Tables in MARTS
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_RETAIL_DB_PROD.MARTS
    TO ROLE BI_READONLY_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA ECOMMERCE_RETAIL_DB_PROD.MARTS
    TO ROLE BI_READONLY_ROLE;

-- PROD FUTURE TABLE/VIEW GRANTS - BI_READONLY_ROLE
-- Future tables
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_RETAIL_DB_PROD.MARTS
    TO ROLE BI_READONLY_ROLE;

-- Future views
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ECOMMERCE_RETAIL_DB_PROD.MARTS
    TO ROLE BI_READONLY_ROLE;
