-- =================================================
-- VERIFY SETUP
-- =================================================

SHOW DATABASES LIKE 'ECOMMERCE_RETAIL_DB%';


-- Verify medallion architecture
SELECT
    'DEV' as database_name,
    'Bronze' as medallion_layer,
    'RAW' as schema_name,
    COUNT(*) as table_count
FROM ECOMMERCE_RETAIL_DB_DEV.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'RAW'

UNION ALL

SELECT 'DEV', 'Silver', 'STAGING', COUNT(*)
FROM ECOMMERCE_RETAIL_DB_DEV.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGING'

UNION ALL

SELECT 'DEV', 'Gold', 'INTERMEDIATE', COUNT(*)
FROM ECOMMERCE_RETAIL_DB_DEV.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'INTERMEDIATE'

UNION ALL

SELECT 'DEV', 'Gold', 'MARTS', COUNT(*)
FROM ECOMMERCE_RETAIL_DB_DEV.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'MARTS'

UNION ALL

SELECT 'PROD', 'Gold', 'INTERMEDIATE', COUNT(*)
FROM ECOMMERCE_RETAIL_DB_PROD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'INTERMEDIATE'

UNION ALL

SELECT 'PROD', 'Gold', 'MARTS', COUNT(*)
FROM ECOMMERCE_RETAIL_DB_PROD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'MARTS'

ORDER BY 1, 2, 3;


-- Verify RAW data was copied
SELECT 'CUSTOMERS' as table_name, COUNT(*) as rows_count FROM ECOMMERCE_RETAIL_DB_DEV.RAW.CUSTOMERS
UNION ALL SELECT 'ORDERS', COUNT(*) FROM ECOMMERCE_RETAIL_DB_DEV.RAW.ORDERS
UNION ALL SELECT 'ORDER_ITEMS', COUNT(*) FROM ECOMMERCE_RETAIL_DB_DEV.RAW.ORDER_ITEMS
UNION ALL SELECT 'PRODUCTS', COUNT(*) FROM ECOMMERCE_RETAIL_DB_DEV.RAW.PRODUCTS;


-- Verify grants are applied correctly:
SHOW GRANTS TO ROLE LEAD_DATA_ENGINEER_ROLE;
SHOW GRANTS TO ROLE BI_READONLY_ROLE;
SHOW GRANTS ON DATABASE ECOMMERCE_RETAIL_DB_DEV;
SHOW GRANTS ON DATABASE ECOMMERCE_RETAIL_DB_PROD;
SHOW GRANTS ON WAREHOUSE ECOMMERCE_RETAIL_WH;