/// BUSINESS MEANING: Master list of marketplace customers (buyers) and where they are located (US geography). GRAIN: one row per customer. RELATIONSHIPS: the customer dimension of the star schema; joins on CUSTOMER_KEY one-to-many to FCT_ORDERS, FCT_ORDER_ITEMS, FCT_ORDER_PAYMENTS and FCT_RFM_SEGMENTS, and one-to-one (bi-directional) to FCT_CLV_CUSTOMER. Use it to break any customer metric down by state or city.
table DIM_CUSTOMERS
	lineageTag: b5f7505e-a37a-47d9-bfd1-99a4d36404b2

	/// Surrogate key for a customer; primary key of this dimension and the join key used by the fact tables. Grain: one per customer.
	column CUSTOMER_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 6c74aeb3-af8c-4da9-96de-ca68650f6db9
		isDefaultLabel
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Natural business identifier of the customer from the source system. Grain: one per customer.
	column CUSTOMER_UNIQUE_ID
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 12d1d742-b3c1-422d-9238-d64f0701fd16
		summarizeBy: none
		sourceColumn: CUSTOMER_UNIQUE_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Customer's 5-digit zip code (most recent address if the customer has multiple orders). Grain: per customer.
	column ZIP_CODE
		dataType: int64
		formatString: 0
		lineageTag: 9bb9e855-7ea0-4a7c-b1fa-2921b600fb31
		summarizeBy: none
		sourceColumn: ZIP_CODE

		annotation SummarizationSetBy = Automatic

	/// Customer's city, title case (most recent address). Grain: per customer.
	column CITY
		dataType: string
		lineageTag: abc99fc1-9c02-4f35-9935-2a408b5911be
		summarizeBy: none
		sourceColumn: CITY

		annotation SummarizationSetBy = Automatic

	/// Customer's US state code, 2-letter (most recent address). Grain: per customer.
	column STATE
		dataType: string
		lineageTag: 215d3dd1-6330-4167-9f98-6e42280485da
		summarizeBy: none
		sourceColumn: STATE

		annotation SummarizationSetBy = Automatic

	partition DIM_CUSTOMERS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    DIM_CUSTOMERS_Table = MARTS_Schema{[Name="DIM_CUSTOMERS",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( DIM_CUSTOMERS_Table ),
				    #"Removed Columns" = Table.RemoveColumns(RemoveMetadaColumns,{"FIRST_ORDER_DATE", "COHORT_MONTH"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"CUSTOMER_KEY", Int64.Type}, {"CUSTOMER_UNIQUE_ID", type text}, {"ZIP_CODE", Int64.Type}, {"CITY", type text}, {"STATE", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

