/// BUSINESS MEANING: Monthly customer-health snapshots combining RFM scoring with churn-risk metrics; use for segmentation, segment migration over time, and churn analysis. GRAIN: one row per customer per snapshot month; metrics are cumulative to that month-end (not per-period). RELATIONSHIPS: joins to DIM_CUSTOMERS (CUSTOMER_KEY) and to DIM_DATES on the snapshot month (SNAPSHOT_DATE_KEY). Excludes canceled/unavailable orders.
table FCT_RFM_SEGMENTS
	lineageTag: 5d5cd826-5672-4bef-93ed-7b84e9a2a9ee

	/// Recency score 1-5 (5=most recent) at the snapshot month. Grain: per customer per snapshot month.
	column R_SCORE
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: ff68920f-034e-4c63-8491-6a6ab8dae151
		summarizeBy: none
		sourceColumn: R_SCORE

		annotation SummarizationSetBy = Automatic

	/// Frequency score 1-5 (5=most frequent) at the snapshot month. Grain: per customer per snapshot month.
	column F_SCORE
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: d5dee23b-64f7-482c-89ad-621d16da7ffc
		summarizeBy: none
		sourceColumn: F_SCORE

		annotation SummarizationSetBy = Automatic

	/// Monetary score 1-5 (5=highest spend) at the snapshot month. Grain: per customer per snapshot month.
	column M_SCORE
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 478d0f75-6885-47a3-8163-040cbd22c5f2
		summarizeBy: none
		sourceColumn: M_SCORE

		annotation SummarizationSetBy = Automatic

	/// Customer's RFM business segment at the snapshot (Champions, New Customers, Loyal Customers, Potential Loyalists, At Risk, Hibernating, Need Attention, Lost). Grain: per customer per snapshot month.
	column RFM_SEGMENT
		dataType: string
		lineageTag: 68d83f58-3e72-429e-9f71-8543c773bfc0
		summarizeBy: none
		sourceColumn: RFM_SEGMENT
		sortByColumn: SEGMENT_INDEX

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Join to DIM_CUSTOMERS. Grain: per customer per snapshot month.
	column CUSTOMER_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: c59f50bd-b787-4755-91f0-bc708d81a311
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Month-end as-of date the snapshot describes; defines the time grain. Grain: the snapshot month.
	column SNAPSHOT_MONTH
		dataType: dateTime
		formatString: Short Date
		lineageTag: ecc89f95-83aa-4bee-ac21-2e49337435b7
		summarizeBy: none
		sourceColumn: SNAPSHOT_MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Days since the customer's last purchase as of the snapshot month-end; lower=more recent. Grain: per customer per snapshot month.
	column RECENCY_DAYS
		dataType: int64
		formatString: 0
		lineageTag: e80cf489-8a25-40fc-9ae4-2bffe8004365
		summarizeBy: none
		sourceColumn: RECENCY_DAYS

		annotation SummarizationSetBy = Automatic

	/// Cumulative orders by the customer through the snapshot month (not per-period). Grain: per customer per snapshot month.
	column TOTAL_ORDERS
		dataType: int64
		formatString: 0
		lineageTag: e89aa42c-907e-4b31-97bb-4c405870486f
		summarizeBy: none
		sourceColumn: TOTAL_ORDERS

		annotation SummarizationSetBy = Automatic

	/// Cumulative revenue by the customer through the snapshot month, BRL (not per-period). Grain: per customer per snapshot month.
	column TOTAL_REVENUE
		dataType: decimal
		formatString: 0.00
		lineageTag: c5fbb83a-02c9-4d96-80fa-63c5e0d01f82
		summarizeBy: none
		sourceColumn: TOTAL_REVENUE

		annotation SummarizationSetBy = Automatic

	/// Weighted average review score (1-5) through the snapshot month; NULL if no reviews. Grain: per customer per snapshot month.
	column AVERAGE_RATING
		dataType: int64
		formatString: 0
		lineageTag: 4251ae54-f116-4c7b-9de1-5d5e19a11d2f
		summarizeBy: none
		sourceColumn: AVERAGE_RATING

		annotation SummarizationSetBy = Automatic

	/// Recency-based churn status at the snapshot (Active, Cooling, At Risk, Churned). Grain: per customer per snapshot month.
	column CHURN_STATUS
		dataType: string
		lineageTag: 8618fdb5-5ece-4580-942d-c9f6cb313bb2
		summarizeBy: none
		sourceColumn: CHURN_STATUS

		annotation SummarizationSetBy = Automatic

	/// Satisfaction tier from rating (promoter, neutral, detractor, unknown). Grain: per customer per snapshot month.
	column CUSTOMER_NPS_SEGMENT
		dataType: string
		lineageTag: 8195307b-20fc-427a-ac90-4fe8b9be2eb8
		summarizeBy: none
		sourceColumn: CUSTOMER_NPS_SEGMENT

		annotation SummarizationSetBy = Automatic

	/// Composite churn-risk score 0-100 (higher=more at risk) at the snapshot. Grain: per customer per snapshot month.
	column CHURN_RISK_SCORE
		dataType: int64
		formatString: 0
		lineageTag: 2d54c0c2-37b9-483d-ab07-dba420f5b9c7
		summarizeBy: none
		sourceColumn: CHURN_RISK_SCORE

		annotation SummarizationSetBy = Automatic

	/// Risk tier from the churn score (Critical, High, Medium, Low). Grain: per customer per snapshot month.
	column CHURN_RISK_SEGMENT
		dataType: string
		lineageTag: 9c9dfa6d-c0da-4a86-b393-ad2d4db00c2f
		summarizeBy: none
		sourceColumn: CHURN_RISK_SEGMENT

		annotation SummarizationSetBy = Automatic

	/// YYYYMMDD key of the snapshot month; join to DIM_DATES. Grain: per customer per snapshot month.
	column SNAPSHOT_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 91c38257-bfc8-4ab1-ade9-0574fe0d022e
		summarizeBy: none
		sourceColumn: SNAPSHOT_DATE_KEY

		annotation SummarizationSetBy = Automatic

	/// Sort index that orders RFM segments consistently (Champions first). Grain: per segment.
	column SEGMENT_INDEX
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bf3e11c4-9c0e-43a8-a398-94cef73d2606
		summarizeBy: none
		sourceColumn: SEGMENT_INDEX

		annotation SummarizationSetBy = Automatic

	/// Sum of R+F+M (3-15); higher=stronger customer at the snapshot. Grain: per customer per snapshot month.
	column RFM_COMBINED_SCORE
		dataType: int64
		formatString: 0
		lineageTag: a0323211-d744-4d5e-a95a-630db9014014
		summarizeBy: none
		sourceColumn: RFM_COMBINED_SCORE

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_RFM_SEGMENT
		dataType: string
		lineageTag: 5ade5194-230c-460a-89a0-e2bcae18d408
		summarizeBy: none
		sourceColumn: PREVIOUS_RFM_SEGMENT

		annotation SummarizationSetBy = Automatic

	column PREVIOUS_SNAPSHOT_MONTH
		dataType: dateTime
		formatString: Short Date
		lineageTag: c766020b-e11a-436c-ae05-8a8a15ca6a80
		summarizeBy: none
		sourceColumn: PREVIOUS_SNAPSHOT_MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FCT_RFM_SEGMENTS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_RFM_SEGMENTS_Table = MARTS_Schema{[Name="FCT_RFM_SEGMENTS",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_RFM_SEGMENTS_Table ),
				    #"Removed Columns" = Table.RemoveColumns(RemoveMetadaColumns,{"CUSTOMER_UNIQUE_ID"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"RECENCY_DAYS", Int64.Type}, {"TOTAL_ORDERS", Int64.Type}, {"AVERAGE_RATING", Int64.Type}, {"R_SCORE", Int64.Type}, {"F_SCORE", Int64.Type}, {"M_SCORE", Int64.Type}, {"RFM_COMBINED_SCORE", Int64.Type}, {"CHURN_RISK_SCORE", Int64.Type}, {"SEGMENT_INDEX", Int64.Type}, {"CUSTOMER_KEY", Int64.Type}, {"SNAPSHOT_MONTH", type date}, {"TOTAL_REVENUE", Currency.Type}, {"CHURN_STATUS", type text}, {"CUSTOMER_NPS_SEGMENT", type text}, {"CHURN_RISK_SEGMENT", type text}, {"RFM_SEGMENT", type text}, {"SNAPSHOT_DATE_KEY", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

