/// BUSINESS MEANING: Retention and revenue-retention (GRR/NRR) of acquisition cohorts over their lifetime. GRAIN: one row per acquisition cohort (COHORT_MONTH) per period offset (PERIOD = months since acquisition). RELATIONSHIPS: pre-aggregated; joins only to DIM_DATES on the cohort month (COHORT_DATE_KEY), with no customer- or order-level relationship. Excludes canceled/unavailable orders and the partial current month.
table FCT_CUSTOMER_RETENTION
	lineageTag: 1aaa95ac-6c83-4579-a7e3-f60987d30806

	column CUSTOMER_RETENTION_KEY
		dataType: int64
		formatString: 0
		lineageTag: 7916c667-f2a7-467c-a52d-fac994b0e857
		summarizeBy: sum
		sourceColumn: CUSTOMER_RETENTION_KEY

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_KEY
		dataType: int64
		formatString: 0
		lineageTag: 7a194953-9cde-42db-9ac6-581918028c87
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		annotation SummarizationSetBy = Automatic

	column COHORT_DATE_KEY
		dataType: int64
		formatString: 0
		lineageTag: b45c0ca9-3f3a-4e51-bea5-4e4df619589b
		summarizeBy: none
		sourceColumn: COHORT_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column PERIOD_DATE_KEY
		dataType: int64
		formatString: 0
		lineageTag: 03afb829-c92c-4403-8b79-e581740ba311
		summarizeBy: sum
		sourceColumn: PERIOD_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column COHORT_MONTH
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1604b7e6-0059-42ed-952f-aa388d82de9d
		summarizeBy: none
		sourceColumn: COHORT_MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PERIOD_MONTH
		dataType: dateTime
		formatString: Short Date
		lineageTag: 20f1792e-55d4-4f6e-9f2a-931f19f139ca
		summarizeBy: none
		sourceColumn: PERIOD_MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column COHORT_PERIOD
		dataType: int64
		formatString: 0
		lineageTag: 4879f75b-ef0f-4800-a566-471939753c34
		summarizeBy: sum
		sourceColumn: COHORT_PERIOD

		annotation SummarizationSetBy = Automatic

	column IS_ACTIVE
		dataType: int64
		formatString: 0
		lineageTag: 14201693-2c19-4674-9dea-aba3af28a167
		summarizeBy: sum
		sourceColumn: IS_ACTIVE

		annotation SummarizationSetBy = Automatic

	column PERIOD_ORDERS
		dataType: int64
		formatString: 0
		lineageTag: 3f3ef42f-c94b-4dad-a072-298c563e7dd5
		summarizeBy: sum
		sourceColumn: PERIOD_ORDERS

		annotation SummarizationSetBy = Automatic

	column PERIOD_REVENUE
		dataType: double
		lineageTag: 931848dd-5e22-431d-a2b2-8ca664c51486
		summarizeBy: sum
		sourceColumn: PERIOD_REVENUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FCT_CUSTOMER_RETENTION = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_COHORT_RETENTION_Table = MARTS_Schema{[Name="FCT_CUSTOMER_RETENTION",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_COHORT_RETENTION_Table ),
				    #"Changed Type" = Table.TransformColumnTypes(RemoveMetadaColumns,{{"CUSTOMER_RETENTION_KEY", Int64.Type}, {"CUSTOMER_KEY", Int64.Type}, {"COHORT_DATE_KEY", Int64.Type}, {"PERIOD_DATE_KEY", Int64.Type}, {"COHORT_MONTH", type date}, {"PERIOD_MONTH", type date}, {"COHORT_PERIOD", Int64.Type}, {"IS_ACTIVE", Int64.Type}, {"PERIOD_ORDERS", Int64.Type}, {"PERIOD_REVENUE", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

