/// BUSINESS MEANING: Payment-transaction facts - one payment on an order, with method, installments and amount. Use for payment-method mix and installment analysis. GRAIN: one row per payment transaction (order x payment sequence x type); excludes canceled/unavailable orders. RELATIONSHIPS: joins to DIM_CUSTOMERS (CUSTOMER_KEY) and DIM_DATES (order date). Not related to FCT_ORDERS - combine only via shared dimensions.
table FCT_ORDER_PAYMENTS
	lineageTag: 2f8d2dab-28cb-405d-95b4-44d14e7309b5

	/// Payment method used (credit_card, boleto, voucher, debit_card, not_defined). Grain: per payment transaction.
	column PAYMENT_TYPE
		dataType: string
		lineageTag: 334d0c4f-a11e-4942-ad28-818ad4b4ad94
		summarizeBy: none
		sourceColumn: PAYMENT_TYPE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Surrogate key of the payment transaction; primary key of this fact. Grain: one per payment transaction.
	column ORDER_PAYMENT_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 4f7890a1-ddea-433e-ae64-573d1fe33be9
		summarizeBy: none
		sourceColumn: ORDER_PAYMENT_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Order this payment belongs to (degenerate reference; no active relationship to FCT_ORDERS). Grain: per payment transaction.
	column ORDER_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: e3365d0a-4946-483f-854d-5efc96f416c7
		summarizeBy: none
		sourceColumn: ORDER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Customer who paid; join to DIM_CUSTOMERS. Grain: per payment transaction.
	column CUSTOMER_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: dab77186-1a03-4898-bc61-1a596af3bf18
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Order placement date; join to DIM_DATES. Grain: per payment transaction.
	column ORDER_DATE_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 79132429-eec4-4fd4-87fa-054f747e4445
		summarizeBy: none
		sourceColumn: ORDER_DATE_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Sequence number of the payment within the order. Grain: per payment transaction.
	column PAYMENT_SEQUENTIAL
		dataType: int64
		formatString: 0
		lineageTag: 3470ba29-ee3f-4fec-85d6-83ef25334b1b
		summarizeBy: none
		sourceColumn: PAYMENT_SEQUENTIAL

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// Number of installments for this payment. Grain: per payment transaction.
	column PAYMENT_INSTALLMENTS
		dataType: int64
		formatString: 0
		lineageTag: c6796c58-1c04-4861-8601-243df9583e2a
		summarizeBy: none
		sourceColumn: PAYMENT_INSTALLMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// Amount of this payment (BRL). Grain: per payment transaction.
	column PAYMENT_VALUE
		dataType: decimal
		formatString: 0.00
		lineageTag: f4e10892-2460-4c1e-87c6-0e1e3b05708c
		summarizeBy: none
		sourceColumn: PAYMENT_VALUE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FCT_ORDER_PAYMENTS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_PAYMENT_ANALYSIS_Table = MARTS_Schema{[Name="FCT_ORDER_PAYMENTS",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_PAYMENT_ANALYSIS_Table ),
				    #"Removed Columns" = Table.RemoveColumns(RemoveMetadaColumns,{"ORDER_ID"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"ORDER_PAYMENT_KEY", Int64.Type}, {"ORDER_KEY", Int64.Type}, {"CUSTOMER_KEY", Int64.Type}, {"ORDER_DATE_KEY", Int64.Type}, {"PAYMENT_TYPE", type text}, {"PAYMENT_SEQUENTIAL", Int64.Type}, {"PAYMENT_INSTALLMENTS", Int64.Type}, {"PAYMENT_VALUE", Currency.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

