/// BUSINESS MEANING: Product co-purchase counts used to compute support, confidence and lift for cross-sell / affinity analysis. GRAIN: one row per product pair. RELATIONSHIPS: joins to DIM_PRODUCTS on product A (active) and product B (inactive; activate with USERELATIONSHIP to resolve the second product). Excludes canceled/unavailable orders.
table FCT_MARKET_BASKET
	lineageTag: a151dc8c-67f0-4c78-a37a-353e565cdc4e

	/// Surrogate key of the product pair; primary key. Grain: one per product pair.
	column BASKET_PAIR_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 5f97b91b-50ad-4ea5-af08-d032885afb3e
		summarizeBy: none
		sourceColumn: BASKET_PAIR_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Number of orders containing both products of the pair (co-occurrence count). Grain: per product pair.
	column PAIR_COUNT
		dataType: int64
		formatString: 0
		lineageTag: 21055157-b651-43e1-835c-9836b681ec8c
		summarizeBy: none
		sourceColumn: PAIR_COUNT

		annotation SummarizationSetBy = User

	/// Orders containing product A; denominator for confidence and lift. Grain: per product pair.
	column PRODUCT_A_ORDER_COUNT
		dataType: int64
		formatString: 0
		lineageTag: b2589798-2f37-435a-bad1-c739a9200337
		summarizeBy: none
		sourceColumn: PRODUCT_A_ORDER_COUNT

		annotation SummarizationSetBy = User

	/// Orders containing product B; used for lift. Grain: per product pair.
	column PRODUCT_B_ORDER_COUNT
		dataType: int64
		formatString: 0
		lineageTag: e6249191-c1b7-428f-b6ef-71d5c308cb1e
		summarizeBy: none
		sourceColumn: PRODUCT_B_ORDER_COUNT

		annotation SummarizationSetBy = User

	/// Product A of the pair; active join to DIM_PRODUCTS. Grain: per product pair.
	column PRODUCT_KEY_A
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 131c6ec1-cc1d-434e-b228-b26043aecbd8
		summarizeBy: none
		sourceColumn: PRODUCT_KEY_A

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Product B of the pair; inactive join to DIM_PRODUCTS. Grain: per product pair.
	column PRODUCT_KEY_B
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: d9ff213a-3bba-4fd8-9141-d1f43701d994
		summarizeBy: none
		sourceColumn: PRODUCT_KEY_B

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FCT_MARKET_BASKET = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_MARKET_BASKET_Table = MARTS_Schema{[Name="FCT_MARKET_BASKET",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_MARKET_BASKET_Table ),
				    #"Changed Type" = Table.TransformColumnTypes(RemoveMetadaColumns,{{"BASKET_PAIR_KEY", Int64.Type}, {"PRODUCT_KEY_A", Int64.Type}, {"PRODUCT_KEY_B", Int64.Type}, {"PAIR_COUNT", Int64.Type}, {"PRODUCT_A_ORDER_COUNT", Int64.Type}, {"PRODUCT_B_ORDER_COUNT", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

