/// BUSINESS MEANING: Customer Lifetime Value - historical value, a 12-month value projection, and behavioral segments (lifecycle, value, satisfaction). Use for customer valuation and finding high-value customers. GRAIN: one row per customer (whole-life summary, not a time series). RELATIONSHIPS: one-to-one (bi-directional) to DIM_CUSTOMERS on CUSTOMER_KEY. It has no date relationship, so its date fields are descriptive attributes and cannot be filtered by DIM_DATES.
table FCT_CLV_CUSTOMER
	lineageTag: b544e3f2-4033-4220-a741-c0e080343fc5

	/// Join to DIM_CUSTOMERS. Grain: one per customer.
	column CUSTOMER_KEY
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 50ffa236-d8ca-46d6-abc4-d77af91f09df
		isDefaultLabel
		summarizeBy: none
		sourceColumn: CUSTOMER_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Customer's acquisition month. Grain: per customer.
	column COHORT_MONTH
		dataType: dateTime
		formatString: Short Date
		lineageTag: 26da7171-fed6-475f-b677-9bf0a6defcdb
		summarizeBy: none
		sourceColumn: COHORT_MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Date of the customer's first order. Grain: per customer.
	column FIRST_ORDER_DATE
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4bfb9560-c5ec-49dc-bcc5-4f025a5f510e
		summarizeBy: none
		sourceColumn: FIRST_ORDER_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Date of the customer's most recent order. Grain: per customer.
	column LAST_ORDER_DATE
		dataType: dateTime
		formatString: Short Date
		lineageTag: fc7fa9c6-68d9-44a5-b5df-ce7b7e31de4d
		summarizeBy: none
		sourceColumn: LAST_ORDER_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Lifetime order count for the customer. Grain: per customer.
	column TOTAL_LIFETIME_ORDERS
		dataType: int64
		formatString: 0
		lineageTag: 79e297c0-dd8f-4284-8e0e-97673a37df6e
		summarizeBy: sum
		sourceColumn: TOTAL_LIFETIME_ORDERS

		annotation SummarizationSetBy = Automatic

	/// Lifetime revenue to date for the customer (BRL). Grain: per customer.
	column TOTAL_LIFETIME_REVENUE
		dataType: decimal
		formatString: 0.00
		lineageTag: 08a0e96a-6f8c-40f8-a38e-4c6091e61d77
		summarizeBy: sum
		sourceColumn: TOTAL_LIFETIME_REVENUE

		annotation SummarizationSetBy = Automatic

	/// Lifetime average order value (revenue/orders, BRL). Grain: per customer.
	column HISTORICAL_AOV
		dataType: decimal
		formatString: 0.00
		lineageTag: ba353c5b-92f4-42b9-b26b-f69bf3a3a70b
		summarizeBy: sum
		sourceColumn: HISTORICAL_AOV

		annotation SummarizationSetBy = Automatic

	/// Days between first and last order; 0 for single-order customers. Grain: per customer.
	column CUSTOMER_LIFESPAN_DAYS
		dataType: int64
		formatString: 0
		lineageTag: 745cfde4-fd15-476f-8356-f6ec9d007833
		summarizeBy: sum
		sourceColumn: CUSTOMER_LIFESPAN_DAYS

		annotation SummarizationSetBy = Automatic

	/// Lifetime number of reviews submitted by the customer. Grain: per customer.
	column TOTAL_REVIEWS
		dataType: int64
		formatString: 0
		lineageTag: 4fb5fc51-2029-4f6a-88f7-f897d31272a6
		summarizeBy: sum
		sourceColumn: TOTAL_REVIEWS

		annotation SummarizationSetBy = Automatic

	/// Lifetime weighted average review score (1-5); NULL if none. Grain: per customer.
	column AVERAGE_RATING
		dataType: int64
		formatString: 0
		lineageTag: 2aa99691-414d-47a5-9278-d000e875949a
		summarizeBy: sum
		sourceColumn: AVERAGE_RATING

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	/// Behavior segment: new (1 order) or returning (2+ orders). Grain: per customer.
	column CUSTOMER_LIFECYCLE_SEGMENT
		dataType: string
		lineageTag: 429288aa-9f9d-4097-ab00-d7a30759119a
		summarizeBy: none
		sourceColumn: CUSTOMER_LIFECYCLE_SEGMENT

		annotation SummarizationSetBy = Automatic

	/// Value tier by lifetime revenue (high_value, medium_value, low_value). Grain: per customer.
	column CUSTOMER_VALUE_SEGMENT
		dataType: string
		lineageTag: db9cae5c-4434-40a5-a2db-e7451a7ab191
		summarizeBy: none
		sourceColumn: CUSTOMER_VALUE_SEGMENT

		annotation SummarizationSetBy = Automatic

	/// Satisfaction tier by average rating (promoter, neutral, detractor, unknown). Grain: per customer.
	column CUSTOMER_SATISFACTION_SEGMENT
		dataType: string
		lineageTag: 01d35262-8042-4fe1-b415-5c48d0219dad
		summarizeBy: none
		sourceColumn: CUSTOMER_SATISFACTION_SEGMENT

		annotation SummarizationSetBy = Automatic

	/// Projected next-12-month customer value (BRL). Grain: per customer.
	column PREDICTED_CLV_12M
		dataType: decimal
		formatString: 0.00
		lineageTag: a2c05c1f-c156-41b3-9d3b-0e7654480a1c
		summarizeBy: sum
		sourceColumn: PREDICTED_CLV_12M

		annotation SummarizationSetBy = Automatic

	partition FCT_CLV_CUSTOMER = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("IFBLGEP-XM39851.snowflakecomputing.com","ECOMMERCE_RETAIL_WH",[Implementation="1.0"]),
				    ECOMMERCE_RETAIL_DB_PROD_Database = Source{[Name="ECOMMERCE_RETAIL_DB_PROD",Kind="Database"]}[Data],
				    MARTS_Schema = ECOMMERCE_RETAIL_DB_PROD_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_CLV_CUSTOMER_Table = MARTS_Schema{[Name="FCT_CLV_CUSTOMER",Kind="Table"]}[Data],
				    RemoveMetadaColumns = fnRemoveMetadataColumns( FCT_CLV_CUSTOMER_Table ),
				    #"Removed Columns" = Table.RemoveColumns(RemoveMetadaColumns,{"CUSTOMER_UNIQUE_ID"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"CUSTOMER_KEY", Int64.Type}, {"COHORT_MONTH", type date}, {"FIRST_ORDER_DATE", type date}, {"LAST_ORDER_DATE", type date}, {"TOTAL_LIFETIME_ORDERS", Int64.Type}, {"TOTAL_LIFETIME_REVENUE", Currency.Type}, {"HISTORICAL_AOV", Currency.Type}, {"CUSTOMER_LIFESPAN_DAYS", Int64.Type}, {"TOTAL_REVIEWS", Int64.Type}, {"AVERAGE_RATING", type number}, {"CUSTOMER_LIFECYCLE_SEGMENT", type text}, {"CUSTOMER_VALUE_SEGMENT", type text}, {"CUSTOMER_SATISFACTION_SEGMENT", type text}, {"PREDICTED_CLV_12M", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

